// Generated by https://pagedraw.io/pages/7992
import React from 'react';
import './loginheader.css';

function render() {
    return <div className="loginheader-loginheader-9">
        <div className="loginheader-0">
            <div className="loginheader-text-8">D A T A A G O R A</div>
        </div>
        <div className="loginheader-1">
            <div className="loginheader-text_2">
                THE FIRST SMART DATA EXCHANGE
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}