// Generated by https://pagedraw.io/pages/7992
import React from 'react';
import ReactDOM from 'react-dom';
import {withRouter} from "react-router-dom";
import Reflux from 'reflux';
import { Link } from 'react-router-dom';
import AuthStore from './../../stores/AuthStore';
import AuthActions from './../../actions/AuthActions';
import './loginform.css';

class LoginForm extends Reflux.Component {

  constructor(props) {
    super(props);
    this.store = AuthStore;
  }

  componentWillUpdate(nextProps, nextState) {
    var isAuthenticated = nextState['isAuthenticated'];
    if (isAuthenticated) {
      this.props.history.push("secret");
    }
  }

  _handleSubmit(event) {
    event.preventDefault();

    AuthActions.login(
      ReactDOM.findDOMNode(this.refs.email).value,//this.state.email,
      ReactDOM.findDOMNode(this.refs.password).value//this.state.password
    );
  }

  render() {
    var errorMessage;
    if (this.state.error) {
      errorMessage = (
        <div className='alert alert-danger padding-bottom alert-dismissible fade show' role="alert">
          { this.state.error }
        </div>
      );
    }

    return (
      <div>
        <form className="login-form col-12 col-sm-12 col-md-4 offset-md-4">

          { errorMessage }

          <div className="form-group">
            <label>Email address</label>
            <input  type="email" ref="email"

              className="form-control" id="inputEmail" placeholder="Enter email" />
          </div>

          <div className="form-group">
            <label>Password</label>
            <input type="password" ref="password"

              className="form-control" id="inputPassword" placeholder="Enter password" />
          </div>

          <div className="form-group text-center">
            <button type="submit" onClick={this._handleSubmit.bind(this)} className="btn btn-transparent">Sign In</button>
          </div>

          <div className="form-group text-center">
            New here? <Link to="signup" className="signup-link" href="#">Sign up!</Link>
          </div>

        </form>
      </div>
    );
  }

  updateEmail(evt) {
   this.setState({
     email: evt.target.value
   });
 }

 updatePassword(evt) {
   this.setState({
     password: evt.target.value
   });
 }
}

export default withRouter(LoginForm);

// import './loginform.css';
//
// function render() {
//     return <div className="loginform-loginform-4">
//         <div className="loginform-0">
//             <div className="loginform-text_3">Email</div>
//         </div>
//         <div className="loginform-1">
//             <input type="text" placeholder="Placeholder" className="loginform-text_input-0" />
//         </div>
//         <div className="loginform-2">
//             <div className="loginform-text_1">Password</div>
//         </div>
//         <div className="loginform-3">
//             <input type="text" placeholder="Placeholder" className="loginform-text_input_2" />
//         </div>
//         <div className="loginform-4">
//             <div onClick={this.props.handleClick} className="loginform-rectangle-8">
//                 <div className="loginform-4-0-0">
//                     <div className="loginform-text_4">Login</div>
//                 </div>
//             </div>
//         </div>
//         <div className="loginform-5">
//             <div className="loginform-text_5">{"New here?"}</div>
//             <div className="loginform-5-1">
//                 <div className="loginform-5-1-0">
//                     <div onClick={this.props.handleClick} className="loginform-text_6">
//                         {"Sign Up!"}
//                     </div>
//                 </div>
//             </div>
//         </div>
//     </div>;
// };
//
// export default function(props) {
//     return render.apply({props: props});
// }
