// Generated by https://pagedraw.io/pages/7992
import Loginheader from './loginheader';
import Loginform from './loginform';
import React from 'react';
import './login.css';

function render() {
    return <div className="login-login-9">
        <div className="login-0">
            <div className="login-loginheader_instance-9">
                <Loginheader /> 
            </div>
        </div>
        <div className="login-1">
            <div className="login-loginform_instance-5">
                <Loginform /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}