// Generated by https://pagedraw.io/pages/7992
import Loginheader from './loginheader';
import Registrationform from './registrationform';
import React from 'react';
import './registration.css';

function render() {
    return <div className="registration-registration-9">
        <div className="registration-0">
            <div className="registration-loginheader_instance_2">
                <Loginheader /> 
            </div>
        </div>
        <div className="registration-1">
            <div className="registration-registrationform_instance-6">
                <Registrationform /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}