import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import './loginform.css';

class RegistationForm extends Component {

  render() {
    return (
      <form className="login-form col-12 col-sm-12 col-md-6 offset-md-3">

        <div className="form-group form-row">
          <div className="col">
            <label htmlFor="inputFname">First name</label>
            <input type="text" className="form-control" id="inputFname" placeholder="First name" />
          </div>
          <div className="col">
            <label htmlFor="inputLname">Last name</label>
            <input type="text" className="form-control" id="inputLname" placeholder="Last Name" />
          </div>
        </div>

        <div className="form-group">
          <label htmlFor="inputOrganization">Organization</label>
          <input type="text" className="form-control" id="inputOrganization" placeholder="Current organization" />
        </div>

        <div className="form-group">
          <label htmlFor="inputPosition">Position</label>
          <input type="text" className="form-control" id="inputPosition" placeholder="Current position" />
        </div>

        <div className="form-group">
          <label htmlFor="inputEmail">Email address</label>
          <input type="email" className="form-control" id="inputEmail" placeholder="Email address" />
        </div>

        <div className="form-group">
          <label htmlFor="inputPassword1">Password</label>
          <input type="password" className="form-control" id="inputPassword1" placeholder="Enter password" />
        </div>

        <div className="form-group">
          <label htmlFor="inputPassword2">Repeat password</label>
          <input type="password" className="form-control" id="inputPassword2" placeholder="Repeat password" />
        </div>

        <div className="form-group text-center">
          <button type="submit" className="btn btn-transparent">Register</button>
        </div>

        <div className="form-group text-center">
          Already a user? <Link to="signin" className="signup-link" href="#">Sign in!</Link>
        </div>
      </form>

    );
  }
}

export default RegistationForm;



// // Generated by https://pagedraw.io/pages/7992
// import React from 'react';
// import './registrationform.css';
//
// function render() {
//     return <div className="registrationform-registrationform-3">
//         <div className="registrationform-0">
//             <div className="registrationform-text_7">First Name</div>
//             <div className="registrationform-text_8">Last Name</div>
//         </div>
//         <div className="registrationform-1">
//             <input type="text" placeholder="Placeholder" className="registrationform-text_input_3" />
//             <input type="text" placeholder="Placeholder" className="registrationform-text_input_4" />
//         </div>
//         <div className="registrationform-2">
//             <div className="registrationform-text_9">Company</div>
//         </div>
//         <div className="registrationform-3">
//             <input type="text" placeholder="Placeholder" className="registrationform-text_input_5" />
//         </div>
//         <div className="registrationform-4">
//             <div className="registrationform-text_1">Email</div>
//         </div>
//         <div className="registrationform-5">
//             <input type="text" placeholder="Placeholder" className="registrationform-text_input_6" />
//         </div>
//         <div className="registrationform-6">
//             <div className="registrationform-text_11">Password</div>
//         </div>
//         <div className="registrationform-7">
//             <input type="text" placeholder="Placeholder" className="registrationform-text_input_7" />
//         </div>
//         <div className="registrationform-8">
//             <div className="registrationform-text_12">
//                 Repeat Password
//             </div>
//         </div>
//         <div className="registrationform-9">
//             <input type="text" placeholder="Placeholder" className="registrationform-text_input_8" />
//         </div>
//         <div className="registrationform-10">
//             <div onClick={this.props.handleClick} className="registrationform-rectangle_4">
//                 <div className="registrationform-10-0-0">
//                     <div className="registrationform-text_13">Sign Up</div>
//                 </div>
//             </div>
//         </div>
//         <div className="registrationform-11">
//             <div className="registrationform-text_5">
//                 {"Already a user?"}
//             </div>
//             <div className="registrationform-11-1">
//                 <div className="registrationform-11-1-0">
//                     <div onClick={this.props.handleClick} className="registrationform-text_6">
//                         {"Log In!"}
//                     </div>
//                 </div>
//             </div>
//         </div>
//     </div>;
// };
//
// export default function(props) {
//     return render.apply({props: props});
// }
