
// Generated by https://pagedraw.io/pages/8816

import React from 'react';
import 'index2.css';


function render() {
    return <div className="frame_2_1-frame_2">
        <div className="frame_2_1-0">
            <div className="frame_2_1-d_a_t_a_s_h_a_r_k-0">
                D A T A S H A R K
            </div>
            <div className="frame_2_1-0-1">
                <div className="frame_2_1-0-1-0">
                    <div className="frame_2_1-vector_4" />
                    <div className="frame_2_1-0-1-0-1">
                        <div className="frame_2_1-0-1-0-1-0">
                            <div className="frame_2_1-vector_5" />
                        </div>
                    </div>
                    <div className="frame_2_1-0-1-0-2">
                        <div className="frame_2_1-0-1-0-2-0">
                            <div className="frame_2_1-vector_5_" />
                        </div>
                    </div>
                </div>
                <div className="frame_2_1-0-1-1">
                    <div className="frame_2_1-vector_5_1" />
                    <div className="frame_2_1-vector_5_5" />
                </div>
                <div className="frame_2_1-0-1-2">
                    <div className="frame_2_1-vector_5_3" />
                </div>
                <div className="frame_2_1-0-1-3">
                    <div className="frame_2_1-vector_5-0" />
                </div>
                <div className="frame_2_1-0-1-4">
                    <div className="frame_2_1-vector_5_9" />
                </div>
                <div className="frame_2_1-0-1-5">
                    <div className="frame_2_1-vector_5_1-0" />
                    <div className="frame_2_1-vector_5_8" />
                </div>
            </div>
            <div className="frame_2_1-0-2">
                <div className="frame_2_1-0-2-0">
                    <div className="frame_2_1-vector_5_11" />
                </div>
                <div className="frame_2_1-0-2-1">
                    <div className="frame_2_1-vector_5_10" />
                </div>
            </div>
            <div className="frame_2_1-0-3">
                <div className="frame_2_1-0-3-0">
                    <div className="frame_2_1-vector_5_6" />
                </div>
            </div>
            <div className="frame_2_1-0-4">
                <div className="frame_2_1-0-4-0">
                    <div className="frame_2_1-vector_5_7" />
                </div>
            </div>
            <div className="frame_2_1-0-5">
                <div className="frame_2_1-0-5-0">
                    <div className="frame_2_1-vector_5_12" />
                </div>
            </div>
            <div className="frame_2_1-0-6">
                <div className="frame_2_1-0-6-0">
                    <div className="frame_2_1-vector_5_13" />
                </div>
            </div>
            <div className="frame_2_1-0-7">
                <div className="frame_2_1-0-7-0">
                    <div className="frame_2_1-vector_5_14" />
                </div>
            </div>
        </div>
        <div className="frame_2_1-1">
            <div className="frame_2_1-1-0">
                <div className="frame_2_1-1-0-0">
                    <div className="frame_2_1-image-7">
                        <div className="frame_2_1-1-0-0-0-0">
                            <div className="frame_2_1-rectangle-0">
                                <div className="frame_2_1-1-0-0-0-0-0-0">
                                    <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/2da7/ab4b/4f2b563a0054b27f61a730929c90ef7f" className="frame_2_1-image-2" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="frame_2_1-1-1">
                <div className="frame_2_1-1-1-0">
                    <div className="frame_2_1-rectangle-00">
                        <div className="frame_2_1-1-1-0-0-0">
                            <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/18a8/2c56/0cc2c39b99f567b6bc72620eaa6fa252" className="frame_2_1-image-0" />
                        </div>
                    </div>
                </div>
            </div>
            <div className="frame_2_1-1-2">
                <div className="frame_2_1-1-2-0">
                    <div className="frame_2_1-rectangle-000">
                        <div className="frame_2_1-1-2-0-0-0">
                            <img src="https://s3-us-west-2.amazonaws.com/figma-alpha/img/f617/4b25/8fd279051b3543d294e110c0e699b205" className="frame_2_1-image-05" />
                        </div>
                    </div>
                </div>
            </div>
            <div className="frame_2_1-1-3">
                <div className="frame_2_1-1-3-0">
                    <div className="frame_2_1-image_2" />
                </div>
            </div>
        </div>
        <div className="frame_2_1-2">
            <div className="frame_2_1-instagram-0">Instagram</div>
            <div className="frame_2_1-facebook-0">Facebook</div>
            <div className="frame_2_1-fitbit-0">Fitbit</div>
        </div>
    </div>;
};

export default function (props) {
    return render.apply({ props: props });
}
